import { basename, extname } from "node:path";

/** MIME type mappings by extension. */
const EXTENSION_MIME_TYPES: Record<string, string> = {
  // Text/code files
  ".txt": "text/plain",
  ".text": "text/plain",
  ".log": "text/plain",
  ".lock": "text/plain",
  ".csv": "text/csv",
  ".tsv": "text/tab-separated-values",
  ".md": "text/markdown",
  ".markdown": "text/markdown",
  ".mdx": "text/markdown",
  ".rst": "text/plain",
  ".adoc": "text/plain",
  ".asciidoc": "text/plain",
  ".ts": "text/typescript",
  ".tsx": "text/typescript",
  ".mts": "text/typescript",
  ".cts": "text/typescript",
  ".js": "text/javascript",
  ".jsx": "text/javascript",
  ".mjs": "text/javascript",
  ".cjs": "text/javascript",
  ".json": "application/json",
  ".jsonl": "application/x-ndjson",
  ".ndjson": "application/x-ndjson",
  ".map": "application/json",
  ".html": "text/html",
  ".htm": "text/html",
  ".css": "text/css",
  ".scss": "text/x-scss",
  ".sass": "text/x-sass",
  ".less": "text/x-less",
  ".xml": "application/xml",
  ".yaml": "text/yaml",
  ".yml": "text/yaml",
  ".toml": "text/x-toml",
  ".ini": "text/x-ini",
  ".properties": "text/plain",
  ".conf": "text/plain",
  ".cfg": "text/plain",
  ".http": "text/plain",
  ".sh": "text/x-shellscript",
  ".bash": "text/x-shellscript",
  ".zsh": "text/x-shellscript",
  ".fish": "text/x-shellscript",
  ".ps1": "text/x-powershell",
  ".psm1": "text/x-powershell",
  ".psd1": "text/x-powershell",
  ".ps1xml": "application/xml",
  ".bat": "text/x-batch",
  ".cmd": "text/x-batch",
  ".py": "text/x-python",
  ".rb": "text/x-ruby",
  ".go": "text/x-go",
  ".rs": "text/x-rust",
  ".java": "text/x-java",
  ".kt": "text/x-kotlin",
  ".kts": "text/x-kotlin",
  ".scala": "text/x-scala",
  ".c": "text/x-c",
  ".h": "text/x-c",
  ".cpp": "text/x-c++",
  ".hpp": "text/x-c++",
  ".cc": "text/x-c++",
  ".cxx": "text/x-c++",
  ".hh": "text/x-c++",
  ".hxx": "text/x-c++",
  ".ipp": "text/x-c++",
  ".tpp": "text/x-c++",
  ".inl": "text/x-c++",
  ".cs": "text/x-csharp",
  ".sln": "text/plain",
  ".csproj": "application/xml",
  ".fsproj": "application/xml",
  ".vbproj": "application/xml",
  ".vcxproj": "application/xml",
  ".vcproj": "application/xml",
  ".props": "application/xml",
  ".targets": "application/xml",
  ".proj": "application/xml",
  ".filters": "application/xml",
  ".swift": "text/x-swift",
  ".m": "text/x-objectivec",
  ".mm": "text/x-objectivec",
  ".php": "text/x-php",
  ".pl": "text/x-perl",
  ".pm": "text/x-perl",
  ".lua": "text/x-lua",
  ".r": "text/x-r",
  ".R": "text/x-r",
  ".asm": "text/x-asm",
  ".s": "text/x-asm",
  ".sql": "text/x-sql",
  ".graphql": "text/x-graphql",
  ".gql": "text/x-graphql",
  ".graphqls": "text/x-graphql",
  ".vue": "text/x-vue",
  ".svelte": "text/x-svelte",
  ".astro": "text/x-astro",
  ".elm": "text/x-elm",
  ".ex": "text/x-elixir",
  ".exs": "text/x-elixir",
  ".erl": "text/x-erlang",
  ".hrl": "text/x-erlang",
  ".hs": "text/x-haskell",
  ".lhs": "text/x-haskell",
  ".clj": "text/x-clojure",
  ".cljs": "text/x-clojure",
  ".cljc": "text/x-clojure",
  ".ml": "text/x-ocaml",
  ".mli": "text/x-ocaml",
  ".fs": "text/x-fsharp",
  ".fsx": "text/x-fsharp",
  ".dart": "text/x-dart",
  ".nim": "text/x-nim",
  ".zig": "text/x-zig",
  ".v": "text/x-v",
  ".sol": "text/x-solidity",
  ".proto": "text/x-protobuf",
  ".prisma": "text/x-prisma",
  ".dockerfile": "text/x-dockerfile",
  ".makefile": "text/x-makefile",
  ".cmake": "text/x-cmake",
  ".gradle": "text/x-gradle",
  // Image files
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".bmp": "image/bmp",
  ".tiff": "image/tiff",
  ".tif": "image/tiff",
  ".avif": "image/avif",
  // Other binary
  ".pdf": "application/pdf",
  ".zip": "application/zip",
  ".tar": "application/x-tar",
  ".gz": "application/gzip",
  ".wasm": "application/wasm",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".eot": "application/vnd.ms-fontobject",
  ".mp3": "audio/mpeg",
  ".wav": "audio/wav",
  ".ogg": "audio/ogg",
  ".mp4": "video/mp4",
  ".webm": "video/webm",
};

const FILE_NAME_MIME_TYPES: Record<string, string> = {
  ".env": "text/plain",
  ".gitignore": "text/plain",
  ".gitattributes": "text/plain",
  ".gitmodules": "text/plain",
  ".gitconfig": "text/plain",
  ".editorconfig": "text/plain",
  ".prettierrc": "application/json",
  ".eslintrc": "application/json",
  ".babelrc": "application/json",
  ".stylelintrc": "text/plain",
  ".npmrc": "text/plain",
  ".nvmrc": "text/plain",
  ".dockerignore": "text/plain",
  ".npmignore": "text/plain",
  ".browserslistrc": "text/plain",
  ".clang-format": "text/plain",
  ".clang-tidy": "text/plain",
  ".yamllint": "text/plain",
  ".markdownlint": "text/plain",
  dockerfile: "text/x-dockerfile",
  containerfile: "text/x-dockerfile",
  makefile: "text/x-makefile",
  gnumakefile: "text/x-makefile",
  "cmakelists.txt": "text/x-cmake",
  justfile: "text/plain",
  procfile: "text/plain",
  gemfile: "text/plain",
  rakefile: "text/plain",
  podfile: "text/plain",
  fastfile: "text/plain",
  appfile: "text/plain",
  brewfile: "text/plain",
  vagrantfile: "text/plain",
  jenkinsfile: "text/plain",
  tiltfile: "text/plain",
  earthfile: "text/plain",
  caddyfile: "text/plain",
};

const TEXT_FILE_EXTENSIONS = new Set([
  ".txt",
  ".text",
  ".log",
  ".lock",
  ".csv",
  ".tsv",
  ".md",
  ".markdown",
  ".mdx",
  ".rst",
  ".adoc",
  ".asciidoc",
  ".ts",
  ".tsx",
  ".mts",
  ".cts",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".json",
  ".jsonl",
  ".ndjson",
  ".map",
  ".html",
  ".htm",
  ".css",
  ".scss",
  ".sass",
  ".less",
  ".xml",
  ".yaml",
  ".yml",
  ".toml",
  ".ini",
  ".properties",
  ".conf",
  ".cfg",
  ".http",
  ".sh",
  ".bash",
  ".zsh",
  ".fish",
  ".ps1",
  ".psm1",
  ".psd1",
  ".ps1xml",
  ".bat",
  ".cmd",
  ".py",
  ".rb",
  ".go",
  ".rs",
  ".java",
  ".kt",
  ".kts",
  ".scala",
  ".c",
  ".h",
  ".cpp",
  ".hpp",
  ".cc",
  ".cxx",
  ".hh",
  ".hxx",
  ".ipp",
  ".tpp",
  ".inl",
  ".cs",
  ".sln",
  ".csproj",
  ".fsproj",
  ".vbproj",
  ".vcxproj",
  ".vcproj",
  ".props",
  ".targets",
  ".proj",
  ".filters",
  ".swift",
  ".m",
  ".mm",
  ".php",
  ".pl",
  ".pm",
  ".lua",
  ".r",
  ".R",
  ".asm",
  ".s",
  ".sql",
  ".graphql",
  ".gql",
  ".graphqls",
  ".vue",
  ".svelte",
  ".astro",
  ".elm",
  ".ex",
  ".exs",
  ".erl",
  ".hrl",
  ".hs",
  ".lhs",
  ".clj",
  ".cljs",
  ".cljc",
  ".ml",
  ".mli",
  ".fs",
  ".fsx",
  ".dart",
  ".nim",
  ".zig",
  ".v",
  ".sol",
  ".proto",
  ".prisma",
  ".dockerfile",
  ".makefile",
  ".cmake",
  ".gradle",
  ".svg",
]);

const TEXT_FILE_NAMES = new Set(Object.keys(FILE_NAME_MIME_TYPES));

function getLowerCaseFileName(filePath: string): string {
  return basename(filePath).toLowerCase();
}

/**
 * Get MIME type from file extension.
 */
export function getMimeType(filePath: string): string {
  const fileName = getLowerCaseFileName(filePath);
  if (FILE_NAME_MIME_TYPES[fileName]) {
    return FILE_NAME_MIME_TYPES[fileName];
  }
  if (fileName.startsWith(".env.")) {
    return "text/plain";
  }

  const ext = extname(filePath).toLowerCase();
  return EXTENSION_MIME_TYPES[ext] || "application/octet-stream";
}

/**
 * Get the HTTP Content-Type header value for a file response.
 * Text-like formats include an explicit UTF-8 charset so browsers do not
 * guess a legacy code page when rendering source files with non-ASCII content.
 */
export function getResponseContentType(filePath: string): string {
  const mimeType = getMimeType(filePath);
  return isTextFilePath(filePath) ? `${mimeType}; charset=utf-8` : mimeType;
}

/**
 * Check whether a path should be treated as a text file.
 */
export function isTextFilePath(filePath: string): boolean {
  const fileName = getLowerCaseFileName(filePath);
  if (TEXT_FILE_NAMES.has(fileName) || fileName.startsWith(".env.")) {
    return true;
  }

  const ext = extname(filePath).toLowerCase();
  return TEXT_FILE_EXTENSIONS.has(ext);
}
